twitter/config/routes.rb
Rails.application.routes.draw do


get "/mod_front" => "tweets#mod_front"


get "/filter_tweets" => "tweets#filter_tweets"

get "/profile" => "users#profile"
resources :tweets do
  get 'set_stat' => 'tweets#set_stat'
  get "indexn"
end
get "/moderator" => 'tweets#moderator'
  resources :users do
    get "/status_set" => 'users#status_set'
  end


  #resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/type_change" => 'users#type_change'
  get "/stats" => "tweets#statistics"
  post 'users/login'
  get "/check_user" => "users#check_user"
  get "/checkmail_user" => "users#checkmail_user"


end

twitter/app/models/user.rb
class User < ApplicationRecord
	mount_uploader :dp, DpUploader
end

twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

  end

  def type_change
	@users = User.all.where("designation != 'admin'").paginate(:page => params[:page], :per_page => 10)
  end
  def status_set
        @user = User.find(params[:user_id])
        @user.update_attributes(:designation => params["format"])
	@query = "$(\"##{params[:user_id]}\").text(\"#{params[:format]}\")"
	render js: @query
  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    if( User.find_by username: params["user"]["username"])
	respond_to do |format|
	  format.html {redirect_to new_user_url, notice: 'Username already exists'}
	end
    elsif(!(params["user"]["password"] .eql? params["user"]["confirm_password"]))
	respond_to do |format|
	  format.html {redirect_to new_user_url, notice: 'Passwords doesnot match'}
	end
    elsif(User.find_by email: params["user"]["email"])
	respond_to do |format|
	  format.html {redirect_to new_user_url, notice: 'Email Id already exists'}
	end
    else
    @user = User.new(user_params)
    @user.designation="user"
    respond_to do |format|
      if @user.save
	session[:username] = params["user"]["username"]
	puts "aaaaaaaaaaaaaaaaaaaaaa"
	puts session[:username]
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
   end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
	if( User.find_by username: params[:uname])

		@newuser = User.find_by username: params[:uname]
		puts @newuser,"aaaaaaaaaaaaaaa"

		if(@newuser[:password] .eql? params[:password])

			respond_to do |format|
				if(@newuser[:designation]) .eql? "moderator"
					session[:username] = params[:uname]
					puts @newuser[:designation]
					format.html { redirect_to new_tweet_url}
				elsif(@newuser[:designation]) .eql? "admin"
					session[:username] = params[:uname]
					puts @newuser[:designation]
					format.html { redirect_to type_change_url}
				else
					format.html { redirect_to new_tweet_url, flash[:notice] => "LoggedIn Successfully" }
					session[:username] = params[:uname]
					#format.json { render :show, status: :created, location: @newuser }
				end
			end
		else
			respond_to do |format|
				format.html {redirect_to users_url, notice: 'Invalid password'}
			end
		end
	#if(@newuser==null)

	else
		respond_to do |format|
			format.html {redirect_to users_url, notice: 'Invalid username'}
		end
	end
end


  def check_user


      @checkuser = User.find_by username: params[:username]
      if @checkuser .nil?

	render js: ""

      elsif(@checkuser[:username] .eql? params[:username])
	render js: "username already exist"
      end

  end

  def checkmail_user


      @checkuser = User.find_by email: params[:email]
      if @checkuser .nil?

	render js: " "

      elsif(@checkuser[:email] .eql? params[:email])
	render js: "email Id already exist"
      end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :email, :designation,:dp)
    end
end

twitter/app/helpers/users_helper.rb
module UsersHelper
end

twitter/app/views/users/_form.html.erb
<%= form_with(model: user, local: true, id: :form1, multipart: true ) do |form| %>




  <div class="field">
    <%= form.label :name ,'NAME' %>
    <%= form.text_field :name, id: :user_name, :required => true, :placeholder => 'Name' %>
  </div>

  <div class="field">
    <%= form.label :username,'USERNAME' %>
    <%= form.text_field :username, id: :user_username, :required => true , :remote => true , onblur: "check()" , onfocus: "remove()", :placeholder => 'Username' %>
    <span id="status">
    </span>
  </div>

  <div class="field">
    <%= form.label :password ,"PASSWORD"%>
    <%= form.password_field :password, id: :user_password ,:required => true, :placeholder => 'Password'%>
  </div>

  <div class="field">
    <%= form.label :confirm_password,'CONFIRM PASSWORD' %>
    <%= form.password_field :confirm_password, id: :user_confirm_password,:required => true ,  onblur: "checkpwd()", :placeholder => 'Confirm Password' %>
    <span id="statuspwd">
    </span>
  </div>

  <div class="field">
    <%= form.label :email,"EMAIL ID" %>
    <%= form.email_field :email, id: :user_email,:required => true , onblur: "checkmail()" , :remote => true, :placeholder => 'Email Id' %>
    <span id="statusmail">
    </span>
  </div>
  <div class="field">
    <%= form.label :dp,"Upload Profile Picture" %><br>
    <%= form.file_field :dp %>
  </div>


  <div class="actions">
    <%= form.submit 'Register' %>
  </div>
<% end %>

<script language="javascript" >
 function check(){
	console.log("check")
        $newvar = $("#user_username").val()
	console.log($newvar)
	$.ajax({
	url: "/check_user",
	type: 'GET',
	data: {username: $newvar },
	success: function(data)
	{
		$('#status').html(data);
		console.log(data)
	}
	});
	}

function checkmail(){
	console.log("checkmail")
        $mailvar = $("#user_email").val()
	console.log($mailvar)
	$.ajax({
	url: "/checkmail_user",
	type: 'GET',
	data: {email: $mailvar },
	success: function(data)
	{
		$('#statusmail').html(data);
		console.log(data)
	}
	});
	}


function checkpwd(){
	console.log("checkpwd")
        $pwdvar = $("#user_password").val()
	$confpwdvar = $("#user_confirm_password").val()
	if($pwdvar == $confpwdvar)
		$('#statuspwd').html("");
	else
		$('#statuspwd').html("Incorrect password");

	/*$.ajax({
	url: "/check_user",
	type: 'GET',
	data: {username: $newvar },
	success: function(data)
	{
		$('#status').html(data);
		console.log(data)
	}
	});*/
	}

function remove(){
	$("#status").html(" ");
}

</script>

twitter/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

twitter/app/views/users/index.html.erb
<body id="loginbod">
  <p id="notice"><%= notice %></p>
<div id="nav"><%= button_to 'SignUp', new_user_path, :method => :get, :id => "sup" %><span id="sgn">Not a member yet?</span></div>
<div id="log">
<div id="p1"><h1>Login</h1><br><br></div>
<div id="log2">
  <br>
<%=form_tag ('/users/login') do%>

 <%= text_field_tag :uname,nil, placeholder: 'Username', class: 'inp'%><br>

 <%= password_field_tag 'password',nil, placeholder: 'Password', class: 'inp' %><br><br>

<div class="row"><br>
 <div class="column"><%= submit_tag "Login", class: "logy" %></div>
<% end %>

</div>
</div>
</div>

twitter/app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<div id="bgimage">
<p>Welcome to Infi_Twitter.<br>Ready to Join?</p>
<div id="reg">
<%= render 'form', user: @user %>
</div>
<%= link_to 'Already a member?', users_path , :id => "back"%>
</div>

twitter/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @user.designation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

twitter/app/views/users/status_set.html.erb
<h1>Tweets</h1>

twitter/app/views/users/type_change.html.erb
<%= stylesheet_link_tag "tables.css" %>
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>
<%= link_to " Logout", users_path, class: 'lnks' %><%= link_to "Stats | ", stats_path,class: 'lnks'  %>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Designation</th>
      <th colspan="4">Update Type</th>

    </tr>
  </thead>

  <tbody>

     <% @users.each do |user| %>
      <tr>
	<td><%= user.username %></td>
        <td><span id="<%= user.id %>"><%= user.designation %></span></td>
        <td><%= link_to 'Moderator', user_status_set_path(user,:moderator),remote: true,id: :moderator %>
        &nbsp; &nbsp;<%= link_to 'User', user_status_set_path(user,:user),remote: true,id: :user %></td>

      </tr>
    <% end %>

  </tbody>
</table>
<%= will_paginate @users %>
<br>