twitter/config/routes.rb
Rails.application.routes.draw do


get "/mod_front" => "tweets#mod_front"


get "/filter_tweets" => "tweets#filter_tweets"

get "/profile" => "users#profile"
resources :tweets do
  get 'set_stat' => 'tweets#set_stat'
  get "indexn"
end
get "/moderator" => 'tweets#moderator'
  resources :users do
    get "/status_set" => 'users#status_set'
  end


  #resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/type_change" => 'users#type_change'
  get "/stats" => "tweets#statistics"
  post 'users/login'
  get "/check_user" => "users#check_user"
  get "/checkmail_user" => "users#checkmail_user"


end

twitter/app/models/tweet.rb
class Tweet < ApplicationRecord
validates :text, presence: true
end

twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :twt, only: [:create, :new, :indexn,:index,:mod_front]

  def index
    @tweets = Tweet.all.paginate(:page => params[:page], :per_page => 10)
  end

  def set_stat

        puts params;
        @tweet = Tweet.find(params[:tweet_id])
        if @tweet.update_attributes(:status => params[:format])
          if @tweet.update_attributes(:approvedby => session[:username])
            @query = "$(\"##{params[:tweet_id]}\").text(\"#{params[:format]}\")"
          else
              @query = "alert('Please Try again')"
          end
        else
            @query = "alert('Please Try again')"
        end
	render js: @query
  end

  def indexn
     	puts params

	if !session[:isnil].eql? "yes"
		puts params[:tweet_id],"aaaaaaaaaaaaaa"
		user=Tweet.find(params[:tweet_id])
	else
		user=User.find(params[:tweet_id])

	end
	@tweets = Tweet.all.where("username= ? AND status='active'",user[:username]).order(created_at: :desc, updated_at: :desc)
	@uname = session[:username]

	puts "aaaaaaaaaaaaaaaaaaaaaaa" +  @uname

  end

  def statistics
	todate =  Date.today.to_s
	@tweets = Tweet.where("created_at like '" +todate +"%' and status like 'active'")
	puts  "aaaaaaaaaaaaaaaaaaaaaaa" ,@tweets
	if(!(@tweets.nil?))
		@today_active = @tweets.length
	else
		@today_active = 0
	end
	@tweets = Tweet.where("created_at like '" +todate +"%' and status like 'inactive'")
	if(!(@tweets.nil?))
	        @today_inactive = @tweets.length
	else
		@today_inactive = 0
	end
	@tweets = Tweet.where("status like 'active'")
	if(!(@tweets.nil?))
		@total_active = @tweets.length
	else
		@total_active = 0
	end
	@tweets = Tweet.where("status like 'inactive'")
	if(!(@tweets.nil?))
		@total_inactive = @tweets.length
	else
		@total_inactive = 0
	end

  end
  def moderator
  end
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new


    @twts = Tweet.all.where("status='active'").order(created_at: :desc, updated_at: :desc)


  end

  # GET /tweets/1/edit
  def edit
  end

    # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.status="inactive"

    @tweet.username=@uname
    @tweets = Tweet.all
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_indexn_url(@tweet), notice: 'Tweet is submitted for approval.' }
        format.json { render :indexn, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_indexn_url(@tweet), notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mod_front
	@tweets = Tweet.all.paginate(:page => params[:page], :per_page => 10)
	render :mod_front
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:username, :text, :status, :approvedby)
    end
    def twt
	@uname = session[:username]
	@twts = Tweet.all.where("status='active'").order(created_at: :desc, updated_at: :desc)
	@usr=Tweet.all.where("username= ? ",@uname)[0]
	uw=User.all.where("username= ? ",@uname)[0][:id]
	if @usr.nil?
		@usr=uw
		session[:isnil]="yes"
	else
		@usr=@usr[:id]
		session[:isnil]="no"
	end
	@type=(User.find_by username: @uname)[:designation]
	puts @type,"ssssssssssssssssssssssssssssss",@usr,@uname
    end
end

twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

twitter/app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :text, id: :tweet_text %>
  </div>

  

  <div class="actions">
    <%= form.submit "Tweet" %>
  </div>
<% end %>

twitter/app/views/tweets/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Text</th>
      <th>Status</th>
      <th>Update Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.username %></td>
        <td><%= tweet.text %></td>
        <td><%= tweet.status %></td>
        <td><%=radio_button("tweet", "update_stat", "active")%>Active<%= radio_button("tweet", "update_stat", "Inactive")%>Inactive</td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

twitter/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "tables.css" %>
<h1>Tweets</h1>
<%= link_to "Logout", users_path, class: 'rite' %><%= link_to @uname+"| ", tweet_indexn_path(@usr),class: 'rite'  %><%= link_to 'Dashboard| ', new_tweet_path,class: 'rite'   %><% if @type .eql? "moderator"%> <%= link_to 'View Tweets|', mod_front_path,class: 'rite'%><%= link_to 'Update Tweets|', tweets_path,class: 'rite'%><% end %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Text</th>
      <th>Status</th>
      <th colspan="4">Update Status</th>

    </tr>
  </thead>

  <tbody>


     <% @tweets.each do |tweet| %>
      <tr >

	<td><%= link_to tweet.username,tweet_indexn_url(tweet) %></td>
        <td><%= tweet.text %></td>
        <td><span id="<%= tweet.id %>"><%= tweet.status %></span></td>
        <td><%= link_to 'Active', tweet_set_stat_path(tweet,:active),remote: true,id: :active %>
        &nbsp; &nbsp;<%= link_to 'Inactive', tweet_set_stat_path(tweet,:inactive),remote: true,id: :inactive %></td>

      </tr>
    <% end %>

  </tbody>
</table>
<%= will_paginate @tweets ,:id => 'page' %>
<br>

twitter/app/views/tweets/indexn.html.erb
<%= stylesheet_link_tag "indexn.css" %>
<p id="notice"><%= notice %></p>
<%= link_to "Logout", users_path, class: 'rite' %><%= link_to @uname+"| ", tweet_indexn_path(@usr),class: 'rite'  %><%= link_to 'Dashboard| ', new_tweet_path,class: 'rite'   %><% if @type .eql? "moderator"%> <%= link_to 'View Tweets|', mod_front_path,class: 'rite'%><%= link_to 'Update Tweets|', tweets_path,class: 'rite'%><% end %>
<h1>Tweets</h1>
<div id="nw">
    <% @tweets.each do |tweet| %>
      <div id="tw">
        <% @us=User.find_by username: tweet.username %>
        <%= image_tag @us.dp_url(:thumb).to_s %>
       <span class="un"><%= tweet.username %></span><span class="dt"><%= tweet.created_at %></span>


</span>
	<br>
       <%= tweet.text %>
        </div>
    <br>
    <% end %>
<br>
</div>
<script language="javascript">
$(document).ready(function(){
$('.dt').each(function(idx,el){
$v=$(el).text();

$y="";
$m="";
$f="";
$a=$v.split(" ");
$d2=$a[0].split("-");
$d = String(new Date());
$d1=$d.split(" ");
switch(parseInt($d2[1]))
{
case 1:$m="Jan";break;
case 2:$m="Feb";break;
case 3:$m="Mar";break;
case 4:$m="Apr";break;
case 5:$m="May";break;
case 6:$m="Jun";break;
case 7:$m="Jul";break;
case 8:$m="Aug";break;
case 9:$m="Sept";break;
case 10:$m="Oct";break;
case 11:$m="Nov";break;
case 12:$m="Dec";break;
}
if($d1[3]==$d2[0])
{
$y="";
}
else
{
$y=$d2[0];
}
if((parseInt($d1[2])-parseInt($d2[2]))==0)
{
	$t1=$a[1].split(":");
	$t2=$d1[4].split(":");
	if((parseInt($t2[0])-parseInt($t1[0]))==0)
	{
	$f=String(parseInt($t2[1])-parseInt($t1[1]))+" min";
	}
	else
	{
	$f=String(parseInt($t2[0])-parseInt($t1[0]))+" hr";
	}
}
else if((parseInt($d1[2])-parseInt($d2[2]))==1)
{
	$f="1d";
}
else
{
	$f=$m+" "+$d2[2]+" "+$y;
}

$(el).text($f);
console.log($f+" "+$el);
});
});
</script>

twitter/app/views/tweets/mod_front.html.erb
<h1>Tweets</h1>
<%= link_to "Logout", users_path, class: 'rite' %><%= link_to @uname+"| ", tweet_indexn_path(@usr),class: 'rite'  %><%= link_to 'Dashboard| ', new_tweet_path,class: 'rite'   %><% if @type .eql? "moderator"%> <%= link_to 'View Tweets|', mod_front_path,class: 'rite'%><%= link_to 'Update Tweets|', tweets_path,class: 'rite'%><% end %>

<table id="display_table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Text</th>
      <th>Status</th>
      <th colspan="3">Filter tweets <br><select id="filter_opt" onchange="filter()">
		 	    <option value="all" selected="true">All Tweets</option>
			    <option value="active">Active Tweets</option>
			    <option value="inactive">Inactive Tweets</option>
			 </select></th>
    </tr>
  </thead>

  <tbody>


     <% @tweets.each do |tweet| %>
      <tr id="<%= tweet.id%>">

	<td><%= link_to tweet.username, tweet_indexn_path(tweet) %></td>
        <td><%= tweet.text %></td>
        <td><%= tweet.status %></span></td>

      </tr>
    <% end %>

  </tbody>
</table>
<%= will_paginate @tweets, :id => 'page' %>
<br>
<script>

function filter(){
    console.log("check");
    var filter = $("#filter_opt").val();
    table = document.getElementById("display_table");
    tr = table.getElementsByTagName("tr");
    if(filter =="all")
    {
	for(i=0;i<tr.length;i++)
		tr[i].style.display=""
	return;
    }
   for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML==filter) {
        tr[i].style.display = "";
	console.log(td.innerHTML)
      } else {
        tr[i].style.display = "none";
      }
    }
  }
    }
</script>

twitter/app/views/tweets/moderator.html.erb
<html>
<body>
<p><%= link_to 'Logout', users_path%></p>
<%= link_to 'View Tweets', mod_front_path%>
<%= link_to 'Update Tweets', tweets_path%>
</body>
</html>

twitter/app/views/tweets/new.html.erb
<%= stylesheet_link_tag "indexn.css" %>

<%= link_to "Logout", users_path, class: 'rite' %><%= link_to @uname+"| ", tweet_indexn_path(@usr),class: 'rite'  %><%= link_to 'Dashboard| ', new_tweet_path,class: 'rite'   %><% if @type .eql? "moderator"%> <%= link_to 'View Tweets|', mod_front_path,class: 'rite'%><%= link_to 'Update Tweets|', tweets_path,class: 'rite'%><% end %>




<h1>Home</h1>
<div id="nw">

<%= render 'form', tweet: @tweet %>

<% @twts.each do |tweet| %>
      <div id="tw">

         <% @us=User.find_by username: tweet.username %>
         <%= image_tag @us.dp_url(:thumb).to_s %>
        <span class="un"> <%= tweet.username%></span><span class="dt"><%= tweet.created_at %></span><br><br>
       <%= tweet.text %>
        </div>
    <br>
    <% end %>
</div>

<script language="javascript">
$(document).ready(function(){
$('.dt').each(function(idx,el){
	$v=$(el).text();
	console.log(el,$v)
	$y="";
	$m="";
	$f="";
	$a=$v.split(" ");
	$d2=$a[0].split("-");
	$d = String(new Date());
	console.log($d);
	$d1=$d.split(" ");
	switch(parseInt($d2[1]))
	{
	case 1:$m="Jan";break;
	case 2:$m="Feb";break;
	case 3:$m="Mar";break;
	case 4:$m="Apr";break;
	case 5:$m="May";break;
	case 6:$m="Jun";break;
	case 7:$m="Jul";break;
	case 8:$m="Aug";break;
	case 9:$m="Sept";break;
	case 10:$m="Oct";break;
	case 11:$m="Nov";break;
	case 12:$m="Dec";break;
	}
	if($d1[3]==$d2[0])
	{
	$y="";
	}
	else
	{
	$y=$d2[0];
	}
	if((parseInt($d1[2])-parseInt($d2[2]))==0)
	{
		$t1=$a[1].split(":");
		$t2=$d1[4].split(":");
		console.log($t1+" "+$t2);
		if((parseInt($t2[0])-parseInt($t1[0]))==0)
		{
		$f=String(parseInt($t2[1])-parseInt($t1[1]))+" min";
		}
		else
		{
		$f=String(parseInt($t2[0])-parseInt($t1[0]))+" hr";
		}
	}
	else if((parseInt($d1[2])-parseInt($d2[2]))==1)
	{
		$f="1d";
	}
	else
	{
		$f=$m+" "+$d2[2]+" "+$y;
	}
	console.log($f);

	$(el).text($f);
	});
});
</script>

twitter/app/views/tweets/set_stat.html.erb
<h1>Tweets</h1>

twitter/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tweet.username %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tweet.status %>
</p>

<p>
  <strong>Approvedby:</strong>
  <%= @tweet.approvedby %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

twitter/app/views/tweets/statistics.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>
<%= link_to " Logout", users_path, class: 'lnks' %><%= link_to "Home | ", type_change_path,class: 'lnks'  %>
<table>
  <thead>
    <tr>
      <th colspan = "2">Today stat</th>
      <th colspan = "2">Total stat</th>
    </tr>
  </thead>

  <tbody>

	<tr>
	<td>Active Tweets</td>
	<td>Inactive Tweets</td>
	<td>Active Tweets</td>
	<td>Inactive Tweets</td>
	</tr>

	<tr>
	<td><%= @today_active %></td>
	<td><%= @today_inactive %></td>
	<td><%= @total_active %></td>
	<td><%= @total_inactive %></td>
	</tr>


  </tbody>
</table>

<br>